#!/usr/bin/python

import sqlite3 as sql
import csv

DB_FILE = "/var/sites/stenosaurus/app/data/stenosaurus.db"
HEADINGS = ['Email', 'Source', 'Subscribed time']

def import_cs_csv(path):
    # Prepare the CSV file for reading.
    csv_file = open(path, 'rU')
    list_reader = csv.reader(csv_file,
                             delimiter=',',
                             quotechar='"',
                             lineterminator='\n')
    headings = list_reader.next()
    if headings != HEADINGS:
        print "Expected headings:\n  %s" % str(HEADINGS)
        print "Actual headings:\n  %s" % str(headings)
        print "Aborting."
        return
    email_index = HEADINGS.index("Email")
    source_index = HEADINGS.index("Source")
    timestamp_index = HEADINGS.index("Subscribed time")

    # Prepare the database for writing.
    db = sql.connect(DB_FILE)

    # Transfer from the CSV file to the database.
    new_signups = []
    for signup in list_reader:
        email = signup[email_index]
        if not email:
            continue
        try:
            db.execute("insert into signups "
                       "(creation,source,email) values (?,?,?)",
                       (signup[timestamp_index],
                        "crowd-supply-prelaunch",
                        email))
            new_signups.append(signup)
            print signup
        except sql.IntegrityError:
            pass
    db.commit()
    print "Added %d new signups." % len(new_signups)

if __name__ == "__main__":
    import sys
    if len(sys.argv) != 2:
        print "Usage: import_cs_list <PATH-TO-CSV-FILE>"
    else:
        path = sys.argv[1]
        import_cs_csv(path)
